### ISSUE TITLE
feat: add copy button for the code preview

### ISSUE THREAD

**Issue by roberthgnz** [eliutgon/buzz-notify-docs#2]
![image](https://github.com/roberthgnz/buzz-notify-docs/assets/63687573/6c3161b4-4dc2-4e6d-98c0-10ddc005e3e5)

**Comment by hardy07** [comment]
can you assign me?

**Comment by roberthgnz** [comment]
> can you assign me?

all yours!

**Comment by hardy07** [comment]
I made a PR. Can you review and merge it?
